name: Deploy to "tuneer.cis188.org"
on: push
jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        run: |
          docker build -t "ghcr.io/tuneerroy/gpt-code-critic/app:${{ github.sha }}" web
      - name: Push images
        if: github.ref == 'refs/heads/main'
        run: |
          docker push "ghcr.io/tuneerroy/gpt-code-critic/app:${{ github.sha }}"
  deploy:
    name: Deploy latest version of code
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir ~/.kube && echo "$KUBECONFIG" > ~/.kube/config && chmod 600 ~/.kube/config
      - name: Update image tag
        run: |
          sed -i "s/IMAGE_TAG/${{ github.sha }}/g" k8s/web.yaml
      - name: Deploy to Kubernetes
        # env:
        #   IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl apply -f k8s/
